### ISSUE TITLE
[bug] The website has a scroll bar.

### ISSUE THREAD

**Issue by abitsalihu** [MainlyColors/codewars-challenge-file-prepare#4]
Hey @MainlyColors, I noticed that everything was centered in the website so there is no need for the website to be longer than the view hight, the body overflows in the Y direction so a scroll bar appears which makes the user believe there is more content below.

I could help with this issue and make a PR. :)

Below is a video of the scroll bar: 

https://user-images.githubusercontent.com/94648837/191086179-cedebd00-7fe0-4ad9-98ec-ebaaea736350.mov

Photo without the scrollbar:

<img width="1437" alt="Screen Shot 2022-09-19 at 20 15 51" src="https://user-images.githubusercontent.com/94648837/191086153-d77362ec-ad8e-4506-8eb1-e8bc98a7d08a.png">

**Comment by MainlyColors** [comment]
@abitsalihu Thanks for pointing that out, The issue seems to be the userAgent is adding margin to body which is causing the scroll to appear in the Y direction since it is set to a `height: 100vh` 

Adding a `margin: 0` to the body should fix it

If you want to make a PR, Go for it 😁

**Comment by abitsalihu** [comment]
@MainlyColors I would be happy to fix it, assign me to this.
Should I also add `overflow:hidden` on the **body** in case any other bugs happens then the overflow will not let the website go past the 100vh and 100vw?

**Comment by MainlyColors** [comment]
@abitsalihu I think of `overflow: hidden` as a quick band-aid/ last resort that leads to confusing bugs down the line. The website should work without it so I would prefer to leave it off.

**Comment by abitsalihu** [comment]
@MainlyColors you are right, I only changed the margin.

I also noticed that the repo does not have a **contribute.md** file, I have a quick template "easy to follow steps for newcomers to contribute" which I use on my repos and other repos that need **contribute.md** files.
 I could add that one if you wish?

**Comment by MainlyColors** [comment]
@abitsalihu I've never set up contribute.md, do you have a link to this template your talking about?

This is also just a small repo to solve a niche problem so might not need one?

**Comment by abitsalihu** [comment]
@MainlyColors `https://github.com/Maianki/Shuttle-UI/blob/dev/CONTRIBUTE.md` this is the one I created for this repo, I have it saved and just change two lines so it matches the repo that needs it, you can just copy it there and use it in your repo if you want.
Very basic first comers guide.

**Comment by MainlyColors** [comment]
@abitsalihu I added it, I like the template. 

Thanks for the link and your help on the PR 😁

**Comment by MainlyColors** [comment]
Issue solved with #5 PR

**Comment by abitsalihu** [comment]
@MainlyColors happy to be able to help. :)
